name: Test on branches
on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 18.x
        uses: actions/setup-node@v6
        with:
          node-version: '22.x'
      - run: npm install
      - run: npm run lint
